-- CreateTable
CREATE TABLE "ClassToday" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "classDate" DATETIME NOT NULL,
    "day" TEXT NOT NULL,
    "noOfClasses" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
